version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: glitchtip
      POSTGRES_USER: glitchtip
      POSTGRES_PASSWORD: glitchtip
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "glitchtip" ]
      interval: 5s
      retries: 5

  redis:
    image: redis:7

  web:
    image: glitchtip/glitchtip:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://glitchtip:glitchtip@postgres:5432/glitchtip
      REDIS_URL: redis://redis:6379
      SECRET_KEY: 034c8380ba3f65743ea6f33256691cf5885bd8d6351bc916309b109c9983aa1a
    ports:
      - "8000:8000"

volumes:
  postgres-data: